In [ ]:
from keras.preprocessing.text import one_hot

In [ ]:
# sentence
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
# create a one hot to convert this sentence
voc_size = 10000

In [ ]:
onehot_rep = [one_hot(words,voc_size)for words in sent]

In [ ]:
onehot_rep

[[5799, 3619, 1114, 561],
 [5799, 3619, 1114, 2365],
 [5799, 9552, 1114, 7314],
 [1353, 779, 8650, 9339, 1042],
 [1353, 779, 8650, 9339, 5243],
 [2022, 5799, 150, 1114, 6220],
 [2515, 5257, 2550, 9339]]

### word embedding

In [ ]:
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences #to make sure sentences size are same
from keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
# padding helps to make the sentence sizes the same by adding zeros to the shorter sentences
# pre is used to create 0 before the sentence and post for vice versa
sent_length = 8
embedded_docs = pad_sequences(onehot_rep,padding= 'pre', maxlen= sent_length)
print(embedded_docs)

[[   0    0    0    0 5799 3619 1114  561]
 [   0    0    0    0 5799 3619 1114 2365]
 [   0    0    0    0 5799 9552 1114 7314]
 [   0    0    0 1353  779 8650 9339 1042]
 [   0    0    0 1353  779 8650 9339 5243]
 [   0    0    0 2022 5799  150 1114 6220]
 [   0    0    0    0 2515 5257 2550 9339]]


In [ ]:
# specify the dimensions for word embedding
dims = 15

In [ ]:
model = Sequential()
model.add(Embedding(voc_size,10, input_length= sent_length))
model.compile(optimizer = 'adam', metrics = ['mse'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs)[0])
# now we can see each word is encoded into a matrix with 10 dimension

1/1 [==============================] - 0s 23ms/step
[[ 0.02106683 -0.04547268 -0.02648388 -0.02927913 -0.0217241   0.04225859
  -0.016005    0.01028129 -0.04709239  0.02175155]
 [ 0.02106683 -0.04547268 -0.02648388 -0.02927913 -0.0217241   0.04225859
  -0.016005    0.01028129 -0.04709239  0.02175155]
 [ 0.02106683 -0.04547268 -0.02648388 -0.02927913 -0.0217241   0.04225859
  -0.016005    0.01028129 -0.04709239  0.02175155]
 [ 0.02106683 -0.04547268 -0.02648388 -0.02927913 -0.0217241   0.04225859
  -0.016005    0.01028129 -0.04709239  0.02175155]
 [ 0.03311253 -0.01756931 -0.04740187  0.01388549 -0.01408589  0.01486653
   0.02525654 -0.03462048 -0.01975858  0.02223295]
 [-0.03653441 -0.02480588  0.02337344 -0.02323476 -0.04334016 -0.04832014
   0.04387852 -0.00178801 -0.01078258 -0.02261176]
 [ 0.01304204 -0.01477716 -0.04641216  0.03479205 -0.04203046  0.01343532
  -0.00110427  0.02112038 -0.01173999 -0.00819776]
 [ 0.00933199  0.00253304  0.04789207 -0.02330451 -0.004635    0.01630951